module.exports = {
  USER_LOADED: "USER_LOADED",
  AUTH_ERROR: "AUTH_ERROR",
  SUCCESS_MESSAGE: "SUCCESS_MESSAGE",
  ERROR_MESSAGE: "ERROR_MESSAGE",
  WARNING_MESSAGE: "WARNING_MESSAGE",
  INFO_MESSAGE: "INFO_MESSAGE",
  USER_LOGOUT:"USER_LOGOUT",
  SET_TRANSPORT_RENT:"SET_TRANSPORT_RENT",
  SET_SINGLE_TRANS_RENT:"SET_SINGLE_TRANS_RENT",
  SET_PARTY:"SET_PARTY",
  SET_BUY:"SET_BUY",
  SET_SELL:"SET_SELL",
  SET_ACCOUNT_LIST:"SET_ACCOUNT_LIST",
  SET_ACCOUNT_DETAILS:"SET_ACCOUNT_DETAILS",
  SET_ITEM_LIST:"SET_ITEM_LIST",
  SET_GODOWN_LIST:"SET_GODOWN_LIST"
};
